export const INTERACT = 'Interact'
export const MOVEUP = 'MoveUp'
export const MOVEDOWN = 'MoveDown'
export const MOVELEFT = 'MoveLeft'
export const MOVERIGHT = 'MoveRight'
export const PAUSE = 'Escape'
export const AXISX = 'axisX'
export const AXISY = 'axisY'
