export enum STATS {
	ATTACK_SPEED = 'ATTACK_SPEED',
	SPEED = 'SPEED',
	DAMAGE = 'DAMAGE',
	CRIT_DAMAGE = 'CRIT_DAMAGE',
	CRIT_CHANCE = 'CRIT_CHANCE',
	KNOCKBACK = 'KNOCKBACK',
	XP_MDOIFIER = 'XP_MDOIFIER',
	DEFENSE = 'DEFENSE',
	MAX_HEALTH = 'MAX_HEALTH',
	MAX_MANA = 'MAX_MANA',
	SPELL_DAMAGE = 'SPELL_DAMAGE',
	REGEN = 'REGEN',
}
